### ISSUE TITLE
Path must be a string

### ISSUE THREAD

**Issue by twifty** [cgalvarez/atom-coverage#15]
When I run the test from within atom, with 'ctrl-shift-Y' or 'window:run-package-specs', I get the following exception:

```
path.js:7 Uncaught (in promise) TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at join (path.js:1211:7)
    at Object.testquire (/home/owen/github/php-interpreter/node_modules/atom-coverage/lib/manager.js:182:21)
```

The head of the test file:
```js
import { testquire } from 'atom-coverage'
const PhpService = testquire('php-service')
```

I have not created any configurations (shouldn't it use the defaults?).

**Comment by twifty** [comment]
I did also try from the command line, and it worked, if I remember correctly.

You say it works for you, just be weary that atom is a pain in the backside for caching things behind your back.

For now, I had to remove the package, as I'm up to my neck with work. I will come back to this issue though, as I really need a visual representation of the coverage within the TextEditor. Once I've finished my current workload, I'll dig into the sources and see if I can't figure out what's going wrong. Unless you fix it first of course ;-)
